# Your name and what you do
name: Julien Déray
bio: Process-oriented Technical Leader

description: Julien's Personal Website

# Profile picture
picture: assets/images/profile.png

# your url: http://USERNAME.github.io
url: https://julienderay.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: Julien_Deray
linkedin: julien-déray-21100b41
github: JulienDeray
email: julien@deray.fr
# google: mygoogle
instagram: julienderay
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Agile Team Leadership, Motivation & Coaching 
    - Certified Scrum Master 
    - Certified Kanban KMP1 
    - Scala 
    - Functional Programming 
    - Reactive Architecture 
    - Stakeholder Management 
    - Information System Analysis & Design 
    - FinTech & Blockchain Technology 

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    blog:
        name: Personal Blog
        description: Check out my blog where I mostly talk about Kanban best practices and personal productivity tools.
        url: https://julienderay.github.io/blog.html
    podcast:
        name: Podcast about Agile Methodologies (French)
        description: A podcast where Pierre Féray-Ferrant and myself exchange monthly about our agile problematics, practices and tools.
        url: https://agilistes.captivate.fm

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
